version: "3.3"
services:
  product-service:
    build:
      context: apps/product-service
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - 8080:8080
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db/product
      QUARKUS_DATASOURCE_USERNAME: product
      QUARKUS_DATASOURCE_PASSWORD: product
    depends_on:
      - db
  coffee-service:
    build:
      context: apps/coffee-service
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - 8081:8080
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db/coffee
      QUARKUS_DATASOURCE_USERNAME: coffee
      QUARKUS_DATASOURCE_PASSWORD: coffee
    depends_on:
      - db
  car-service:
    build:
      context: apps/car-service
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - 8082:8080
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db/car
      QUARKUS_DATASOURCE_USERNAME: car
      QUARKUS_DATASOURCE_PASSWORD: car
    depends_on:
      - db
  db:
    build: tools/local/postgres
    ports:
      - 65432:5432
    volumes:
      - postgresVolume:/var/lib/postgresql/data
    environment:
      POSTGRES_MULTIPLE_DATABASES: car,coffee,product
      POSTGRES_USER: ilyes
      POSTGRES_PASSWORD: zouaoui
#  if using .env file for values then use the following
#      POSTGRES_MULTIPLE_DATABASES: $POSTGRES_MULTIPLE_DATABASES
#      POSTGRES_USER: $POSTGRES_USER
#      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
volumes:
  postgresVolume:
  pgadmin: